AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/IndentationWidth:
  Width: 2

Layout/EmptyLines:
  Enabled: true

Metrics/MethodLength:
  Max: 15
