name: 'Lintic - Automated Linting Fixes'
description: 'Automatically fix linting errors in Ruby files using AI'
author: 'Lintic Team'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  ollama-model:
    description: 'Ollama model to use for AI fixes'
    required: false
    default: 'qwen2.5-coder:1.5b'
  ollama-uri:
    description: 'Ollama server URI'
    required: false
    default: 'http://localhost:11434/v1/'
  openai-api-key:
    description: 'OpenAI API key (if not using Ollama)'
    required: false
    default: 'ollama'
  ruby-version:
    description: 'Ruby version to use'
    required: false
    default: '3.1'

outputs:
  fixes-applied:
    description: 'Number of files that were fixed'
    value: ${{ steps.run-lintic.outputs.fixes-applied }}
  pr-created:
    description: 'URL of the created fix PR (if any)'
    value: ${{ steps.run-lintic.outputs.pr-url }}

runs:
  using: 'composite'
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}

    - name: Install Ruby dependencies
      shell: bash
      run: |
        gem install dotenv octokit ruby-openai rubocop

    - name: Run Lintic
      id: run-lintic
      shell: bash
      env:
        LINTIC_GITHUB_TOKEN: ${{ inputs.github-token }}
        LINTIC_GITHUB_REPO: ${{ github.repository }}
        LINTIC_GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
        LINTIC_OLLAMA_MODEL: ${{ inputs.ollama-model }}
        LINTIC_OLLAMA_URI: ${{ inputs.ollama-uri }}
        LINTIC_OPENAI_API_KEY: ${{ inputs.openai-api-key }}
      run: |
        # Copy the Lintic script to current directory
        cp ${{ github.action_path }}/main.rb ./lintic.rb

        # Run Lintic and capture output
        OUTPUT=$(ruby lintic.rb 2>&1)
        echo "$OUTPUT"

        # Extract metrics (simple parsing)
        FIXES_APPLIED=$(echo "$OUTPUT" | grep -o "Successfully processed [0-9]\+ files" | grep -o "[0-9]\+" || echo "0")
        PR_URL=$(echo "$OUTPUT" | grep -o "https://github.com/.*/pull/[0-9]\+" || echo "")

        echo "fixes-applied=$FIXES_APPLIED" >> $GITHUB_OUTPUT
        echo "pr-url=$PR_URL" >> $GITHUB_OUTPUT

    - name: Cleanup
      if: always()
      shell: bash
      run: |
        rm lintic.rb

branding:
  icon: 'zap'
  color: 'green'
